---
# Source: imagepuller/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: release-name-imagepuller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: imagepuller
      helm.sh/chart: imagepuller-0.1.0
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/version: "1.0"
      app.kubernetes.io/managed-by: Tiller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: imagepuller
        helm.sh/chart: imagepuller-0.1.0
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/managed-by: Tiller
    spec:
      initContainers:
      - name: init-puller
        image: quay.io/rhpipeline/skopeo:alpine
        command:
          - "skopeo"
          - "copy"
          - "docker://index.docker.io/from/this:tag"
          - "docker-daemon:to/that:tag"
        volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
